/*
 * @Author: Whzcorcd
 * @Date: 2021-11-29 13:50:59
 * @LastEditors: Whzcorcd
 * @LastEditTime: 2021-12-12 18:07:56
 * @Description: file content
 */
'use strict'

const fs = require('fs')
const { generate } = require('@gdyfe/dockerfile-generator')
const { regionProductPath } = require('./target')

const endOfLine = require('os').EOL
const write = (file, data) => {
  fs.writeFileSync(file, data + endOfLine)
}

const generateDockerfile = async options => {
  const deploy = options.deploy

  const input = {
    comment: 'Generated by Frontend-Build-Service for GCloud',
    from: { baseImage: 'nginx:latest' },
    run: [
      'mkdir -p /usr/share/nginx/www',
      'mkdir -p /etc/nginx/ssl',
      'rm -rf /etc/nginx/nginx.conf',
    ],
    copy: {
      './nginx.conf': '/etc/nginx/nginx.conf',
      './ssl': '/etc/nginx/ssl',
      './app': '/usr/share/nginx/www',
    },
    expose: [`${deploy.ports.http || 80}`, `${deploy.ports.https || 443}`],
  }

  const result = await generate(input)
  write(`${regionProductPath(deploy.target, deploy.region)}/Dockerfile`, result)
}

module.exports = generateDockerfile
